---

- name: Install mariadb-server if file exists
  hosts: all
  become: yes

  tasks:

  - name:  Check if file is exists
    shell: "test -f /tmp/database"
    register: is_exists

  - name: Install mariadb-server
    yum:
      name: mariadb-server
      state: latest
    when: is_exists == 1

  - name: Start and Enable mariadb-server
    service: name=mariadb state=started enabled=yes

  - name: Create a new database
    mysql_db: name=database state=present
