---

- name: Install mariadb-server if file exists
  hosts: all
  become: yes

  tasks:

  - name:  Check if file is exists
    shell: test -f /tmp/database %%echo "#FILE is exists"
    register: result

  - name: Install mariadb-server
    yum:
      name: mariadb-server
      state: latest
    when: result.stdout | length > 0

  - name: Start and Enable mariadb-server
    service: name=mariadb state=started enabled=yes
